# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dalfox < Formula
  desc "DalFox(Finder Of XSS) / Parameter Analysis and XSS Scanning tool based on golang"
  homepage "https://www.hahwul.com"
  version "2.5.1"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hahwul/dalfox/releases/download/v2.5.1/dalfox_2.5.1_darwin_amd64.tar.gz"
      sha256 "320f5b7588ef4ab3d175efc0b25ffdb631e53342fd851957408015099d9ab8f4"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hahwul/dalfox/releases/download/v2.5.1/dalfox_2.5.1_linux_amd64.tar.gz"
      sha256 "683cec09d2e3e7cae5dd424349b6bc674c85759ccefcb4f8203b2356182c3425"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/hahwul/dalfox/releases/download/v2.5.1/dalfox_2.5.1_linux_armv6.tar.gz"
      sha256 "64f5a3d69a4e2b4bce658b3afcb64975d5172b4427be2af47686027ea441d256"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hahwul/dalfox/releases/download/v2.5.1/dalfox_2.5.1_linux_arm64.tar.gz"
      sha256 "829e89efd82d2ba0aba3c416e1d002489a23a570c73eafee7cdc8939da797cc4"
    end
  end

  def install
    bin.install "dalfox"
  end

  test do
    system "#{bin}/dalfox version"
  end
end
