# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dalfox < Formula
  desc "DalFox(Finder Of XSS) / Parameter Analysis and XSS Scanning tool based on golang"
  homepage "https://www.hahwul.com"
  version "2.4.1"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hahwul/dalfox/releases/download/v2.4.1/dalfox_2.4.1_darwin_amd64.tar.gz"
      sha256 "72b65e26629a4e94413b42d1470cdd08323a6c06f7a2f643de3cdfdb14fc7758"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hahwul/dalfox/releases/download/v2.4.1/dalfox_2.4.1_linux_amd64.tar.gz"
      sha256 "2ae55e74f62c0e8f9d4daede90328cdb5b82a0fbf729f07ea39b3129a2b37036"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/hahwul/dalfox/releases/download/v2.4.1/dalfox_2.4.1_linux_armv6.tar.gz"
      sha256 "6b85f74b2e65712a4188b3fe56977349743dc262f6a800983f4c37b7ff077ef3"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hahwul/dalfox/releases/download/v2.4.1/dalfox_2.4.1_linux_arm64.tar.gz"
      sha256 "0168a8fb9bc1dd5221300668a2753d10ca50c662da880cefbb865946fbbe6a4f"
    end
  end

  def install
    bin.install "dalfox"
  end

  test do
    system "#{bin}/dalfox version"
  end
end
